Homework6
unfalse/nodejs-course-2021-homeworks pull request #12
Opened 2021-07-25 20:21 UTC by unfalse

2021-07-30 18:49 UTC, serp-ya requested changes
Выглядит не плохо, первая задача решена верно. Единственное, что я бы посоветовал - сделать общее для приложения миддлвари, которое решало бы 2й критерий (`Add a middleware which will proxy all the requests (except login) and check that HTTP Authorization header has the correct value of JWT token.`). В этой миддлвари можно перечислить все урл, которые надо исключить из проверки, и не придётся на каждый роут навешивать доп обработчик для аутентификации

Не вижу добавления корса:
TASK 6.2
Add CORS middleware to access service methods from WEB applications hosted on another domains (https://github.com/expressjs/cors).

2021-07-30 18:49 UTC, serp-ya commented on src/hw6/controllers/groupsController.ts
> +    async create(group: Group): Promise<object> {
Почему тут пострадала типизация?

2021-07-30 18:49 UTC, serp-ya commented on src/hw6/controllers/tokenController.ts
> +    async add(tokenAuth: TokenModelAuth): Promise<void> {
Отсюда не плохо бы возвращать какой-то результат, хотя бы булеан

2021-07-30 18:49 UTC, serp-ya commented on src/hw6/controllers/tokenController.ts
> +                // @ts-ignore
Почему приходится что-то игнорить?

2021-07-30 18:49 UTC, serp-ya commented on src/hw6/lib/bcrypt.ts
> +    SALT_ROUNDS: 10 as number,
`10 as number`?

2021-07-30 18:49 UTC, serp-ya commented on src/hw6/middlewares/auth.ts
> +        verifyToken(accessToken, TOKEN_TYPES.ACCESS);
Кажется, что здесь не хватает обработки. Если токен не валидный, то мы просто идём дальше

2021-07-30 18:49 UTC, serp-ya commented on src/hw6/models/constants.ts
> +export const UNAUTHORIZED = 401;
Годно

2021-07-31 13:04 UTC, unfalse commented on src/hw6/controllers/groupsController.ts
> +    async create(group: Group): Promise<object> {
Тут что угодно может прийти в catch, поэтому решил поставить object.

2021-07-31 13:14 UTC, unfalse commented on src/hw6/controllers/tokenController.ts
> +                // @ts-ignore
Не разобрался с типами тут, что-то монструозное требуется.

2021-07-31 13:15 UTC, unfalse commented on src/hw6/lib/bcrypt.ts
> +    SALT_ROUNDS: 10 as number,
убрал

2021-07-31 13:27 UTC, unfalse commented on src/hw6/middlewares/auth.ts
> +        verifyToken(accessToken, TOKEN_TYPES.ACCESS);
Там в случае невалидного токена или ошибок происходит throw, поэтому смысла проверять нет, только если колбэк указать четвертым параметром.

2021-08-02 09:20 UTC, serp-ya approved these changes
Отлично!

2021-10-19 01:39 UTC, merged