homework with CRUD user service
unfalse/nodejs-course-2021-homeworks pull request #2
Opened 2021-04-11 09:16 UTC by unfalse

2021-04-11 18:00 UTC, ReshetovItsMe requested changes
reviewed

2021-04-11 18:00 UTC, ReshetovItsMe commented on package.json
>    "main": "index.js",
нет линтера,  в задании сказано подключить, есть ссылка на конфиг файл

2021-04-11 18:00 UTC, ReshetovItsMe commented on src/hw2/validation.ts
> +} from 'express-joi-validation'
это не совсем чистый joi. 
еще странно что валидация на create и update разная. 
при создании получается не нужно указать id, а при update нужно. может апдейтить просто по логину и его делать уникальным при создании нового?

p.s. просто вкусовщина, исправлять не обязательно.

2021-04-11 18:00 UTC, ReshetovItsMe commented on src/hw2/requests.ts
> +let users: Array<User> = [];
лучше логику сохранения юзера вынести куда-то, это не должно храниться в мидлваре, можно создать какой-то синглетон класс и там сделать геттеры и сеттеры.

2021-04-11 18:00 UTC, ReshetovItsMe commented on src/hw2/requests.ts
> +const getAutoSuggestUsers = (loginSubstring: string, limit: number): User[] =>
это тоже не должно находиться в мидлваре, это бизнес логика

2021-04-11 19:44 UTC, unfalse commented on src/hw2/validation.ts
> +} from 'express-joi-validation'
Первый раз слышу что при создании записи в БД нужно указывать id :)
А так конечно про логин при апдейте - резонно.
Но уж как есть, так есть.

2021-04-11 19:45 UTC, unfalse commented on src/hw2/requests.ts
> +let users: Array<User> = [];
Это не мидлварь.

2021-04-11 19:45 UTC, unfalse commented on src/hw2/requests.ts
> +const getAutoSuggestUsers = (loginSubstring: string, limit: number): User[] =>
Никто не говорил о соблюдении архитектуры :)

2021-04-11 19:46 UTC, unfalse commented on package.json
>    "main": "index.js",
Хорошо, добавлю.

2021-04-11 19:47 UTC, ReshetovItsMe commented on src/hw2/validation.ts
> +} from 'express-joi-validation'
никто не говорил что при создании нужно указывать id

2021-04-11 19:48 UTC, ReshetovItsMe commented on src/hw2/requests.ts
> +let users: Array<User> = [];
если это не мидлварь, тут не должно быть работы с реквестом, сюда должен быть передан уже объект и произведена какая-то с ним работа. реквесты обрабатываются в мидлварях

2021-04-11 19:49 UTC, unfalse commented on package.json
>    "main": "index.js",
У меня ts, для него должен быть tslint. Ссылка есть только на eslint.

2021-04-11 19:49 UTC, ReshetovItsMe commented on src/hw2/requests.ts
> +let users: Array<User> = [];
ну и респонс соотвественно должен отправляться тоже из мидлвари. 
сейчас это выглядит как мидлварь

2021-04-11 19:50 UTC, ReshetovItsMe commented on package.json
>    "main": "index.js",
tslint deprecated :) 
eslint можно использовать с ts

2021-04-11 19:51 UTC, ReshetovItsMe commented on package.json
>    "main": "index.js",
![image](https://user-images.githubusercontent.com/19675225/114319059-7fc3f080-9b18-11eb-989c-634b1f8a2d77.png)

2021-04-12 02:49 UTC, unfalse commented on package.json
>    "main": "index.js",
Ок, вижу.

2021-04-12 02:51 UTC, unfalse commented on src/hw2/validation.ts
> +} from 'express-joi-validation'
![image](https://user-images.githubusercontent.com/1831217/114334371-de628c00-9b63-11eb-8524-5a3cfdcb05b1.png)

2021-04-12 02:54 UTC, unfalse commented on src/hw2/validation.ts
> +} from 'express-joi-validation'
Ну я если id укажу в валидации при создании, то придется его указывать. Смысла нет в этом.
Хотя наверное правило валидации одно будет при использовании логина вместо id, когда апдейтишь. Подумаю.

2021-04-14 09:56 UTC, ReshetovItsMe approved these changes

2021-04-14 11:24 UTC, merged